CREATE TABLE IF NOT EXISTS Customer (id INT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS Transaction (id INT PRIMARY KEY AUTO_INCREMENT, customer_id INT NOT NULL, amount DECIMAL(10, 2) NOT NULL, transaction_date DATE NOT NULL, FOREIGN KEY (customer_id) REFERENCES Customer(id));